parcelRequire=function(e,r,t,n){var i,o="function"==typeof parcelRequire&&parcelRequire,u="function"==typeof require&&require;function f(t,n){if(!r[t]){if(!e[t]){var i="function"==typeof parcelRequire&&parcelRequire;if(!n&&i)return i(t,!0);if(o)return o(t,!0);if(u&&"string"==typeof t)return u(t);var c=new Error("Cannot find module '"+t+"'");throw c.code="MODULE_NOT_FOUND",c}p.resolve=function(r){return e[t][1][r]||r},p.cache={};var l=r[t]=new f.Module(t);e[t][0].call(l.exports,p,l,l.exports,this)}return r[t].exports;function p(e){return f(p.resolve(e))}}f.isParcelRequire=!0,f.Module=function(e){this.id=e,this.bundle=f,this.exports={}},f.modules=e,f.cache=r,f.parent=o,f.register=function(r,t){e[r]=[function(e,r){r.exports=t},{}]};for(var c=0;c<t.length;c++)try{f(t[c])}catch(e){i||(i=e)}if(t.length){var l=f(t[t.length-1]);"object"==typeof exports&&"undefined"!=typeof module?module.exports=l:"function"==typeof define&&define.amd?define(function(){return l}):n&&(this[n]=l)}if(parcelRequire=f,i)throw i;return f}({"oXx+":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.initializeTaskerJs=exports.taskerUtilities=void 0;const e={inspect:e=>{const t=[];return JSON.stringify(e,function(e,r){if("object"==typeof r&&null!==r){if(-1!==t.indexOf(r))return;t.push(r)}return r})},makeConsole:t=>({log(...r){t.flash(r.map(t=>"string"==typeof t?t:e.inspect(t)).join(" "))}}),getParams:e=>(e.par||[]).map(e=>{let t;try{t=JSON.parse(e)}catch(r){t=e}return"undefined"===t?void 0:t}),getLocals:t=>{const r=e.getParams(t),s=r[1],o=s&&"object"==typeof s?r[1]:null;if(o)return{par:o.par||[],caller:o.caller||[],...o};const l=r[0],i=(l&&"object"==typeof l?l:{})||{};return{...(t.local_keys||[]).reduce((e,r)=>{const s=r.slice(1);return e[s]=t.local(s),e},{}),...i,par:r,caller:[...t.caller||[],...i.caller||[]]}}};exports.taskerUtilities=e;const t=t=>(t.inspect=e.inspect,t.console=e.makeConsole(t),t.locals=e.getLocals(t),t);exports.initializeTaskerJs=t;
},{}],"XCAL":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=exports.parseCallerId=exports.ROUTE_TYPE=void 0;const e={Enter:"enter",Exit:"exit"};exports.ROUTE_TYPE=e;const t=(t="")=>{const[r,...s]=t.split("="),o=s.join("=");switch(r){case"profile":{const[e,...t]=o.split(":");return{type:e,route:t.join(":")}}case"task":return{type:e.Enter,route:o};default:return{type:e.Enter,route:t}}};exports.parseCallerId=t;class r{constructor(e,t){this.context=t,this.routes=e,this.routes._errorHandler||(this.routes._errorHandler={enter(){t.console.log("No route matched")},exit(){}})}dispatch(e){return Promise.resolve().then(()=>{const r=e.caller&&e.caller[e.caller.length-1],s=t(r);return(this.routes[s.route]||this.routes._errorHandler)[s.type](e,this.context)})}}exports.default=r;
},{}],"8U54":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=require("./tasker"),t=r(require("./router"));function r(e){return e&&e.__esModule?e:{default:e}}window.tasker=(0,e.initializeTaskerJs)(window);const a={Environment:tasker.global("TJS_ENV"),RemoteUrl:tasker.global("TJS_DEV_REMOTE"),LocalPath:tasker.global("TJS_LOCAL_PATH")},s={RunScript:"TJS:RunScript"},l=()=>"development"!==a.Environment?Promise.resolve():fetch(a.RemoteUrl).then(e=>e.text()).then(e=>{tasker.readFile(a.LocalPath)!==e&&(tasker.writeFile(a.LocalPath,e),tasker.flash("script updated"),tasker.performTask(s.RunScript,tasker.local("priority"),"null",JSON.stringify(tasker.locals)),tasker.exit())}).catch(e=>tasker.flash(e.message));class o{constructor(e){this.router=new t.default(e,tasker),l().then(()=>this.router.dispatch(tasker.locals).catch(e=>tasker.flash(e.message)).then(()=>tasker.exit()))}}exports.default=o;
},{"./tasker":"oXx+","./router":"XCAL"}],"pfd8":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.startTask=void 0;var t={enter:function(t,e){e.flash("Starting task")},exit:function(t,e){}};exports.startTask=t;
},{}],"cPI2":[function(require,module,exports) {
"use strict";var e=t(require("tasker-js-runner")),r=require("./modules/timeManager");function t(e){return e&&e.__esModule?e:{default:e}}new e.default({taskStart:r.startTask});
},{"tasker-js-runner":"8U54","./modules/timeManager":"pfd8"}]},{},["cPI2"], null)