parcelRequire=function(e,r,t,n){var i,o="function"==typeof parcelRequire&&parcelRequire,u="function"==typeof require&&require;function f(t,n){if(!r[t]){if(!e[t]){var i="function"==typeof parcelRequire&&parcelRequire;if(!n&&i)return i(t,!0);if(o)return o(t,!0);if(u&&"string"==typeof t)return u(t);var c=new Error("Cannot find module '"+t+"'");throw c.code="MODULE_NOT_FOUND",c}p.resolve=function(r){return e[t][1][r]||r},p.cache={};var l=r[t]=new f.Module(t);e[t][0].call(l.exports,p,l,l.exports,this)}return r[t].exports;function p(e){return f(p.resolve(e))}}f.isParcelRequire=!0,f.Module=function(e){this.id=e,this.bundle=f,this.exports={}},f.modules=e,f.cache=r,f.parent=o,f.register=function(r,t){e[r]=[function(e,r){r.exports=t},{}]};for(var c=0;c<t.length;c++)try{f(t[c])}catch(e){i||(i=e)}if(t.length){var l=f(t[t.length-1]);"object"==typeof exports&&"undefined"!=typeof module?module.exports=l:"function"==typeof define&&define.amd?define(function(){return l}):n&&(this[n]=l)}if(parcelRequire=f,i)throw i;return f}({"bjhr":[function(require,module,exports) {
var e=6e4;module.exports=function(t){var n=new Date(t.getTime()),r=n.getTimezoneOffset();n.setSeconds(0,0);var o=n.getTime()%e;return r*e+o};
},{}],"CFBi":[function(require,module,exports) {
function e(e){return e instanceof Date}module.exports=e;
},{}],"ajCz":[function(require,module,exports) {
var e=require("../_lib/getTimezoneOffsetInMilliseconds/index.js"),t=require("../is_date/index.js"),r=36e5,n=6e4,a=2,i=/[T ]/,l=/:/,u=/^(\d{2})$/,s=[/^([+-]\d{2})$/,/^([+-]\d{3})$/,/^([+-]\d{4})$/],d=/^(\d{4})/,c=[/^([+-]\d{4})/,/^([+-]\d{5})/,/^([+-]\d{6})/],f=/^-(\d{2})$/,p=/^-?(\d{3})$/,v=/^-?(\d{2})-?(\d{2})$/,D=/^-?W(\d{2})$/,o=/^-?W(\d{2})-?(\d{1})$/,x=/^(\d{2}([.,]\d*)?)$/,I=/^(\d{2}):?(\d{2}([.,]\d*)?)$/,$=/^(\d{2}):?(\d{2}):?(\d{2}([.,]\d*)?)$/,g=/([Z+-].*)$/,m=/^(Z)$/,T=/^([+-])(\d{2})$/,w=/^([+-])(\d{2}):?(\d{2})$/;function C(r,i){if(t(r))return new Date(r.getTime());if("string"!=typeof r)return new Date(r);var l=(i||{}).additionalDigits;l=null==l?a:Number(l);var u=F(r),s=U(u.date,l),d=s.year,c=y(s.restDateString,d);if(c){var f,p=c.getTime(),v=0;if(u.time&&(v=Y(u.time)),u.timezone)f=z(u.timezone)*n;else{var D=p+v,o=new Date(D);f=e(o);var x=new Date(D);x.setDate(o.getDate()+1);var I=e(x)-e(o);I>0&&(f+=I)}return new Date(p+v+f)}return new Date(r)}function F(e){var t,r={},n=e.split(i);if(l.test(n[0])?(r.date=null,t=n[0]):(r.date=n[0],t=n[1]),t){var a=g.exec(t);a?(r.time=t.replace(a[1],""),r.timezone=a[1]):r.time=t}return r}function U(e,t){var r,n=s[t],a=c[t];if(r=d.exec(e)||a.exec(e)){var i=r[1];return{year:parseInt(i,10),restDateString:e.slice(i.length)}}if(r=u.exec(e)||n.exec(e)){var l=r[1];return{year:100*parseInt(l,10),restDateString:e.slice(l.length)}}return{year:null}}function y(e,t){if(null===t)return null;var r,n,a;if(0===e.length)return(n=new Date(0)).setUTCFullYear(t),n;if(r=f.exec(e))return n=new Date(0),a=parseInt(r[1],10)-1,n.setUTCFullYear(t,a),n;if(r=p.exec(e)){n=new Date(0);var i=parseInt(r[1],10);return n.setUTCFullYear(t,0,i),n}if(r=v.exec(e)){n=new Date(0),a=parseInt(r[1],10)-1;var l=parseInt(r[2],10);return n.setUTCFullYear(t,a,l),n}return(r=D.exec(e))?h(t,parseInt(r[1],10)-1):(r=o.exec(e))?h(t,parseInt(r[1],10)-1,parseInt(r[2],10)-1):null}function Y(e){var t,a,i;if(t=x.exec(e))return(a=parseFloat(t[1].replace(",",".")))%24*r;if(t=I.exec(e))return a=parseInt(t[1],10),i=parseFloat(t[2].replace(",",".")),a%24*r+i*n;if(t=$.exec(e)){a=parseInt(t[1],10),i=parseInt(t[2],10);var l=parseFloat(t[3].replace(",","."));return a%24*r+i*n+1e3*l}return null}function z(e){var t,r;return(t=m.exec(e))?0:(t=T.exec(e))?(r=60*parseInt(t[2],10),"+"===t[1]?-r:r):(t=w.exec(e))?(r=60*parseInt(t[2],10)+parseInt(t[3],10),"+"===t[1]?-r:r):0}function h(e,t,r){t=t||0,r=r||0;var n=new Date(0);n.setUTCFullYear(e,0,4);var a=7*t+r+1-(n.getUTCDay()||7);return n.setUTCDate(n.getUTCDate()+a),n}module.exports=C;
},{"../_lib/getTimezoneOffsetInMilliseconds/index.js":"bjhr","../is_date/index.js":"CFBi"}],"KKv9":[function(require,module,exports) {
var e=require("../parse/index.js");function r(r,i){var t=e(r),n=e(i);return t.getTime()-n.getTime()}module.exports=r;
},{"../parse/index.js":"ajCz"}],"F5+8":[function(require,module,exports) {
var e=require("../difference_in_milliseconds/index.js"),r=6e4;function i(i,n){var o=e(i,n)/r;return o>0?Math.floor(o):Math.ceil(o)}module.exports=i;
},{"../difference_in_milliseconds/index.js":"KKv9"}],"Sjwe":[function(require,module,exports) {
var e=require("../difference_in_milliseconds/index.js");function r(r,i){var n=e(r,i)/1e3;return n>0?Math.floor(n):Math.ceil(n)}module.exports=r;
},{"../difference_in_milliseconds/index.js":"KKv9"}],"lvwL":[function(require,module,exports) {
var e=require("../difference_in_milliseconds/index.js"),r=36e5;function i(i,n){var o=e(i,n)/r;return o>0?Math.floor(o):Math.ceil(o)}module.exports=i;
},{"../difference_in_milliseconds/index.js":"KKv9"}],"JXAh":[function(require,module,exports) {
var e=require("../parse/index.js");function r(r,n){var t=e(r).getTime(),u=Number(n);return new Date(t+u)}module.exports=r;
},{"../parse/index.js":"ajCz"}],"4ip+":[function(require,module,exports) {
var e=require("../add_milliseconds/index.js");function r(r,d){var i=Number(d);return e(r,-i)}module.exports=r;
},{"../add_milliseconds/index.js":"JXAh"}],"+vZp":[function(require,module,exports) {
var e=require("../add_milliseconds/index.js"),r=6e4;function d(d,i){var n=Number(i);return e(d,n*r)}module.exports=d;
},{"../add_milliseconds/index.js":"JXAh"}],"wdQF":[function(require,module,exports) {
var e=require("../add_minutes/index.js");function r(r,u){var n=Number(u);return e(r,-n)}module.exports=r;
},{"../add_minutes/index.js":"+vZp"}],"cFoC":[function(require,module,exports) {
var e=require("../add_milliseconds/index.js"),r=36e5;function d(d,i){var n=Number(i);return e(d,n*r)}module.exports=d;
},{"../add_milliseconds/index.js":"JXAh"}],"oWR9":[function(require,module,exports) {
var r=require("../add_hours/index.js");function e(e,u){var d=Number(u);return r(e,-d)}module.exports=e;
},{"../add_hours/index.js":"cFoC"}],"9n5r":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.calculateRunningTime=exports.calculatePauseTime=void 0;var e=o(require("date-fns/difference_in_milliseconds")),r=o(require("date-fns/difference_in_minutes")),n=o(require("date-fns/difference_in_seconds")),t=o(require("date-fns/difference_in_hours")),u=o(require("date-fns/sub_milliseconds")),i=o(require("date-fns/sub_minutes")),a=o(require("date-fns/sub_hours"));function o(e){return e&&e.__esModule?e:{default:e}}function f(e,r){return l(e)||c(e,r)||s()}function s(){throw new TypeError("Invalid attempt to destructure non-iterable instance")}function c(e,r){var n=[],t=!0,u=!1,i=void 0;try{for(var a,o=e[Symbol.iterator]();!(t=(a=o.next()).done)&&(n.push(a.value),!r||n.length!==r);t=!0);}catch(f){u=!0,i=f}finally{try{t||null==o.return||o.return()}finally{if(u)throw i}}return n}function l(e){if(Array.isArray(e))return e}var d=function(){for(var r=arguments.length>0&&void 0!==arguments[0]?arguments[0]:[],n=0,t=0,u=r.length;t+1<u;t+=2)n+=(0,e.default)(r[t+1],r[t]);return n};exports.calculatePauseTime=d;var _=function(e,u){var o=(0,t.default)(u,e),f=(0,a.default)(u,o),s=(0,r.default)(f,e);return[o,s,(0,n.default)((0,i.default)(f,s),e)]},v=function(e,r,n){var t=d(n),i=(0,u.default)(r||Date.now(),t),a=f(_(e,i),3),o=a[0],s=a[1],c=a[2];return"".concat(o," hours ").concat(s," min. ").concat(c," sec.")};exports.calculateRunningTime=v;
},{"date-fns/difference_in_milliseconds":"KKv9","date-fns/difference_in_minutes":"F5+8","date-fns/difference_in_seconds":"Sjwe","date-fns/difference_in_hours":"lvwL","date-fns/sub_milliseconds":"4ip+","date-fns/sub_minutes":"wdQF","date-fns/sub_hours":"oWR9"}]},{},["9n5r"], null)