parcelRequire=function(e,r,t,n){var i,o="function"==typeof parcelRequire&&parcelRequire,u="function"==typeof require&&require;function f(t,n){if(!r[t]){if(!e[t]){var i="function"==typeof parcelRequire&&parcelRequire;if(!n&&i)return i(t,!0);if(o)return o(t,!0);if(u&&"string"==typeof t)return u(t);var c=new Error("Cannot find module '"+t+"'");throw c.code="MODULE_NOT_FOUND",c}p.resolve=function(r){return e[t][1][r]||r},p.cache={};var l=r[t]=new f.Module(t);e[t][0].call(l.exports,p,l,l.exports,this)}return r[t].exports;function p(e){return f(p.resolve(e))}}f.isParcelRequire=!0,f.Module=function(e){this.id=e,this.bundle=f,this.exports={}},f.modules=e,f.cache=r,f.parent=o,f.register=function(r,t){e[r]=[function(e,r){r.exports=t},{}]};for(var c=0;c<t.length;c++)try{f(t[c])}catch(e){i||(i=e)}if(t.length){var l=f(t[t.length-1]);"object"==typeof exports&&"undefined"!=typeof module?module.exports=l:"function"==typeof define&&define.amd?define(function(){return l}):n&&(this[n]=l)}if(parcelRequire=f,i)throw i;return f}({"bjhr":[function(require,module,exports) {
var e=6e4;module.exports=function(t){var n=new Date(t.getTime()),r=n.getTimezoneOffset();n.setSeconds(0,0);var o=n.getTime()%e;return r*e+o};
},{}],"CFBi":[function(require,module,exports) {
function e(e){return e instanceof Date}module.exports=e;
},{}],"ajCz":[function(require,module,exports) {
var e=require("../_lib/getTimezoneOffsetInMilliseconds/index.js"),t=require("../is_date/index.js"),r=36e5,n=6e4,a=2,i=/[T ]/,l=/:/,u=/^(\d{2})$/,s=[/^([+-]\d{2})$/,/^([+-]\d{3})$/,/^([+-]\d{4})$/],d=/^(\d{4})/,c=[/^([+-]\d{4})/,/^([+-]\d{5})/,/^([+-]\d{6})/],f=/^-(\d{2})$/,p=/^-?(\d{3})$/,v=/^-?(\d{2})-?(\d{2})$/,D=/^-?W(\d{2})$/,o=/^-?W(\d{2})-?(\d{1})$/,x=/^(\d{2}([.,]\d*)?)$/,I=/^(\d{2}):?(\d{2}([.,]\d*)?)$/,$=/^(\d{2}):?(\d{2}):?(\d{2}([.,]\d*)?)$/,g=/([Z+-].*)$/,m=/^(Z)$/,T=/^([+-])(\d{2})$/,w=/^([+-])(\d{2}):?(\d{2})$/;function C(r,i){if(t(r))return new Date(r.getTime());if("string"!=typeof r)return new Date(r);var l=(i||{}).additionalDigits;l=null==l?a:Number(l);var u=F(r),s=U(u.date,l),d=s.year,c=y(s.restDateString,d);if(c){var f,p=c.getTime(),v=0;if(u.time&&(v=Y(u.time)),u.timezone)f=z(u.timezone)*n;else{var D=p+v,o=new Date(D);f=e(o);var x=new Date(D);x.setDate(o.getDate()+1);var I=e(x)-e(o);I>0&&(f+=I)}return new Date(p+v+f)}return new Date(r)}function F(e){var t,r={},n=e.split(i);if(l.test(n[0])?(r.date=null,t=n[0]):(r.date=n[0],t=n[1]),t){var a=g.exec(t);a?(r.time=t.replace(a[1],""),r.timezone=a[1]):r.time=t}return r}function U(e,t){var r,n=s[t],a=c[t];if(r=d.exec(e)||a.exec(e)){var i=r[1];return{year:parseInt(i,10),restDateString:e.slice(i.length)}}if(r=u.exec(e)||n.exec(e)){var l=r[1];return{year:100*parseInt(l,10),restDateString:e.slice(l.length)}}return{year:null}}function y(e,t){if(null===t)return null;var r,n,a;if(0===e.length)return(n=new Date(0)).setUTCFullYear(t),n;if(r=f.exec(e))return n=new Date(0),a=parseInt(r[1],10)-1,n.setUTCFullYear(t,a),n;if(r=p.exec(e)){n=new Date(0);var i=parseInt(r[1],10);return n.setUTCFullYear(t,0,i),n}if(r=v.exec(e)){n=new Date(0),a=parseInt(r[1],10)-1;var l=parseInt(r[2],10);return n.setUTCFullYear(t,a,l),n}return(r=D.exec(e))?h(t,parseInt(r[1],10)-1):(r=o.exec(e))?h(t,parseInt(r[1],10)-1,parseInt(r[2],10)-1):null}function Y(e){var t,a,i;if(t=x.exec(e))return(a=parseFloat(t[1].replace(",",".")))%24*r;if(t=I.exec(e))return a=parseInt(t[1],10),i=parseFloat(t[2].replace(",",".")),a%24*r+i*n;if(t=$.exec(e)){a=parseInt(t[1],10),i=parseInt(t[2],10);var l=parseFloat(t[3].replace(",","."));return a%24*r+i*n+1e3*l}return null}function z(e){var t,r;return(t=m.exec(e))?0:(t=T.exec(e))?(r=60*parseInt(t[2],10),"+"===t[1]?-r:r):(t=w.exec(e))?(r=60*parseInt(t[2],10)+parseInt(t[3],10),"+"===t[1]?-r:r):0}function h(e,t,r){t=t||0,r=r||0;var n=new Date(0);n.setUTCFullYear(e,0,4);var a=7*t+r+1-(n.getUTCDay()||7);return n.setUTCDate(n.getUTCDate()+a),n}module.exports=C;
},{"../_lib/getTimezoneOffsetInMilliseconds/index.js":"bjhr","../is_date/index.js":"CFBi"}],"pfSt":[function(require,module,exports) {
var e=require("../parse/index.js");function r(r,i){var t=e(r).getTime(),n=e(i).getTime();return t>n?-1:t<n?1:0}module.exports=r;
},{"../parse/index.js":"ajCz"}],"KKv9":[function(require,module,exports) {
var e=require("../parse/index.js");function r(r,i){var t=e(r),n=e(i);return t.getTime()-n.getTime()}module.exports=r;
},{"../parse/index.js":"ajCz"}],"Sjwe":[function(require,module,exports) {
var e=require("../difference_in_milliseconds/index.js");function r(r,i){var n=e(r,i)/1e3;return n>0?Math.floor(n):Math.ceil(n)}module.exports=r;
},{"../difference_in_milliseconds/index.js":"KKv9"}],"mgfB":[function(require,module,exports) {
var e=require("../parse/index.js");function r(r,t){var n=e(r),u=e(t);return 12*(n.getFullYear()-u.getFullYear())+(n.getMonth()-u.getMonth())}module.exports=r;
},{"../parse/index.js":"ajCz"}],"+NJC":[function(require,module,exports) {
var e=require("../parse/index.js");function r(r,i){var t=e(r).getTime(),n=e(i).getTime();return t<n?-1:t>n?1:0}module.exports=r;
},{"../parse/index.js":"ajCz"}],"5KzI":[function(require,module,exports) {
var e=require("../parse/index.js"),r=require("../difference_in_calendar_months/index.js"),n=require("../compare_asc/index.js");function a(a,i){var s=e(a),t=e(i),o=n(s,t),d=Math.abs(r(s,t));return s.setMonth(s.getMonth()-o*d),o*(d-(n(s,t)===-o))}module.exports=a;
},{"../parse/index.js":"ajCz","../difference_in_calendar_months/index.js":"mgfB","../compare_asc/index.js":"+NJC"}],"LeeW":[function(require,module,exports) {
function o(){var o={lessThanXSeconds:{one:"less than a second",other:"less than {{count}} seconds"},xSeconds:{one:"1 second",other:"{{count}} seconds"},halfAMinute:"half a minute",lessThanXMinutes:{one:"less than a minute",other:"less than {{count}} minutes"},xMinutes:{one:"1 minute",other:"{{count}} minutes"},aboutXHours:{one:"about 1 hour",other:"about {{count}} hours"},xHours:{one:"1 hour",other:"{{count}} hours"},xDays:{one:"1 day",other:"{{count}} days"},aboutXMonths:{one:"about 1 month",other:"about {{count}} months"},xMonths:{one:"1 month",other:"{{count}} months"},aboutXYears:{one:"about 1 year",other:"about {{count}} years"},xYears:{one:"1 year",other:"{{count}} years"},overXYears:{one:"over 1 year",other:"over {{count}} years"},almostXYears:{one:"almost 1 year",other:"almost {{count}} years"}};return{localize:function(e,t,n){var s;return n=n||{},s="string"==typeof o[e]?o[e]:1===t?o[e].one:o[e].other.replace("{{count}}",t),n.addSuffix?n.comparison>0?"in "+s:s+" ago":s}}}module.exports=o;
},{}],"UV3R":[function(require,module,exports) {
var r=["M","MM","Q","D","DD","DDD","DDDD","d","E","W","WW","YY","YYYY","GG","GGGG","H","HH","h","hh","m","mm","s","ss","S","SS","SSS","Z","ZZ","X","x"];function D(D){var e=[];for(var n in D)D.hasOwnProperty(n)&&e.push(n);var o=r.concat(e).sort().reverse();return new RegExp("(\\[[^\\[]*\\])|(\\\\)?("+o.join("|")+"|.)","g")}module.exports=D;
},{}],"b/WI":[function(require,module,exports) {
var r=require("../../_lib/build_formatting_tokens_reg_exp/index.js");function e(){var e=["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],t=["January","February","March","April","May","June","July","August","September","October","November","December"],u=["Su","Mo","Tu","We","Th","Fr","Sa"],a=["Sun","Mon","Tue","Wed","Thu","Fri","Sat"],o=["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"],d=["AM","PM"],i=["am","pm"],c=["a.m.","p.m."],M={MMM:function(r){return e[r.getMonth()]},MMMM:function(r){return t[r.getMonth()]},dd:function(r){return u[r.getDay()]},ddd:function(r){return a[r.getDay()]},dddd:function(r){return o[r.getDay()]},A:function(r){return r.getHours()/12>=1?d[1]:d[0]},a:function(r){return r.getHours()/12>=1?i[1]:i[0]},aa:function(r){return r.getHours()/12>=1?c[1]:c[0]}};return["M","D","DDD","d","Q","W"].forEach(function(r){M[r+"o"]=function(e,t){return n(t[r](e))}}),{formatters:M,formattingTokensRegExp:r(M)}}function n(r){var e=r%100;if(e>20||e<10)switch(e%10){case 1:return r+"st";case 2:return r+"nd";case 3:return r+"rd"}return r+"th"}module.exports=e;
},{"../../_lib/build_formatting_tokens_reg_exp/index.js":"UV3R"}],"N6L2":[function(require,module,exports) {
var e=require("./build_distance_in_words_locale/index.js"),r=require("./build_format_locale/index.js");module.exports={distanceInWords:e(),format:r()};
},{"./build_distance_in_words_locale/index.js":"LeeW","./build_format_locale/index.js":"b/WI"}],"HLwM":[function(require,module,exports) {
var e=require("../compare_desc/index.js"),n=require("../parse/index.js"),r=require("../difference_in_seconds/index.js"),s=require("../difference_in_months/index.js"),a=require("../locale/en/index.js"),i=1440,o=2520,t=43200,u=86400;function d(d,f,l){var c=l||{},h=e(d,f),x=c.locale,M=a.distanceInWords.localize;x&&x.distanceInWords&&x.distanceInWords.localize&&(M=x.distanceInWords.localize);var X,m,T={addSuffix:Boolean(c.addSuffix),comparison:h};h>0?(X=n(d),m=n(f)):(X=n(f),m=n(d));var v,S=r(m,X),j=m.getTimezoneOffset()-X.getTimezoneOffset(),q=Math.round(S/60)-j;if(q<2)return c.includeSeconds?S<5?M("lessThanXSeconds",5,T):S<10?M("lessThanXSeconds",10,T):S<20?M("lessThanXSeconds",20,T):S<40?M("halfAMinute",null,T):M(S<60?"lessThanXMinutes":"xMinutes",1,T):0===q?M("lessThanXMinutes",1,T):M("xMinutes",q,T);if(q<45)return M("xMinutes",q,T);if(q<90)return M("aboutXHours",1,T);if(q<i)return M("aboutXHours",Math.round(q/60),T);if(q<o)return M("xDays",1,T);if(q<t)return M("xDays",Math.round(q/i),T);if(q<u)return M("aboutXMonths",v=Math.round(q/t),T);if((v=s(m,X))<12)return M("xMonths",Math.round(q/t),T);var z=v%12,_=Math.floor(v/12);return z<3?M("aboutXYears",_,T):z<9?M("overXYears",_,T):M("almostXYears",_+1,T)}module.exports=d;
},{"../compare_desc/index.js":"pfSt","../parse/index.js":"ajCz","../difference_in_seconds/index.js":"Sjwe","../difference_in_months/index.js":"5KzI","../locale/en/index.js":"N6L2"}],"jUDc":[function(require,module,exports) {
var e=require("../distance_in_words/index.js");function n(n,r){return e(Date.now(),n,r)}module.exports=n;
},{"../distance_in_words/index.js":"HLwM"}],"Wjjo":[function(require,module,exports) {
var global = arguments[3];
var e=arguments[3],n=t(require("date-fns/distance_in_words_to_now"));function t(e){return e&&e.__esModule?e:{default:e}}var r=function(e){return(0,n.default)(Number(e))},u=function(t){return(0,n.default)(Number(e(t)))};window.timeSince=r,window.timeSinceGlobal=u;
},{"date-fns/distance_in_words_to_now":"jUDc"}]},{},["Wjjo"], null)
//# sourceMappingURL=/time-since.js.map